"""
酸素骨格をPDB形式で出力する（ATOMのみ、CONECTなし）。
結合は3Dmol側で距離ベース表示。水の酸素は OW（dopant等と区別）。
gromacs.py とは異なり、水素の配置（depol_loop）を必要としない。
"""
import numpy as np
from cif2ice import cellshape


def _cell_to_cryst1(cell_nm: np.ndarray) -> str:
    """セル行列（nm）からPDB CRYST1行を生成。a,b,cはオングストロームに変換。"""
    a, b, c, alpha, beta, gamma = cellshape(cell_nm)
    # cellshape は nm を返す。PDB はオングストローム
    a, b, c = a * 10, b * 10, c * 10
    return (
        f"CRYST1{a:9.3f}{b:9.3f}{c:9.3f}"
        f"{alpha:7.2f}{beta:7.2f}{gamma:7.2f}"
        " P 1           1\n"
    )


def lattice_sites_to_pdb(
    lattice_sites_frac: np.ndarray,
    graph,
    cell: np.ndarray,
) -> str:
    """
    格子サイト（酸素のみ）と水素結合グラフからPDB文字列を生成。

    Args:
        lattice_sites_frac: 分数座標 (N, 3)
        graph: networkx Graph、ノードはサイトインデックス、辺は水素結合
        cell: 3x3 セル行列（nm）

    Returns:
        PDB形式の文字列。ATOM のみ（CONECT は出さない。結合は3Dmol側で距離ベース表示）。
        residue番号は水分子インデックス+1。水の酸素は OW。
    """
    # 分数座標 → デカルト（nm）
    cart = lattice_sites_frac @ cell
    # PDBはオングストロームが一般的だが、3Dmol.jsはnmも可。nmのまま渡す。
    # 他のツールとの互換性のためオングストロームに変換する場合:
    # cart_ang = cart * 10
    # ここではnmのまま（3Dmol.jsは両方読める）
    cart_ang = cart * 10  # nm -> Angstrom（PDBの慣例）

    lines = []
    lines.append("REMARK   Generated by GenIce3 API (oxygen skeleton + H-bonds)")
    lines.append(_cell_to_cryst1(cell))

    # ATOM行（酸素のみ、1分子=1残基、resseq = 水分子インデックス+1）
    # 水の酸素は OW（dopant等の酸素Oと区別するため）
    for i, pos in enumerate(cart_ang):
        serial = i + 1
        resseq = i + 1
        line = (
            f"ATOM  {serial:5d}  OW  SOL W{resseq:4d}    "
            f"{pos[0]:8.3f}{pos[1]:8.3f}{pos[2]:8.3f}"
            "  1.00  0.00           O\n"
        )
        lines.append(line)

    # CONECTは出力しない。3Dmol側で距離ベースの結合表示を行う。
    lines.append("END\n")
    return "".join(lines)
